name: "🚀 Feature request"
description: "Suggest a new feature or improvement for this project."
title: "[FEATURE REQUEST] - "
labels:
  - "enhancement"
  - "feature request"
assignees: ""
body:
  - type: markdown
    attributes:
      value: |
        ### Is your feature request related to a problem?
        A clear and concise description of the problem. Example: "I'm always frustrated when..."

  - type: textarea
    id: problem_description
    attributes:
      label: "Problem description"
      description: "Describe the problem related to your feature request (if any)."
      placeholder: "Describe the problem here..."

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature description"
      description: "Describe the feature you'd like to add or improve."
      placeholder: "Describe the new feature here..."

  - type: textarea
    id: benefit_explanation
    attributes:
      label: "How would this feature improve the project?"
      description: "Explain how this feature would solve the problem or improve the project."
      placeholder: "Describe how this feature will benefit the project..."

  - type: textarea
    id: alternative_solutions
    attributes:
      label: "Alternative solutions"
      description: "If you have considered alternative solutions, describe them here."
      placeholder: "Describe alternative solutions here..."

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Add more details here..."

  - type: checkboxes
    id: priority
    attributes:
      label: "Feature priority"
      options:
        - label: "Critical"
          description: "This feature is urgent and critical."
        - label: "Important"
          description: "This feature is important for the evolution of the project."
        - label: "Nice to have"
          description: "This feature would be good to have, but it's not critical."
