name: "🚀 Feature request"
description: "Suggest a new feature or improvement for this project."
title: "feat: "
labels:
  - "enhancement"
  - "feature request"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### Is your feature request related to a problem?
        A clear and concise description of the problem. Example: "I'm always frustrated when..."

  - type: textarea
    id: problem_description
    attributes:
      label: "Problem description"
      description: "Describe the problem related to your feature request (if any)."
      placeholder: "Describe the problem here..."

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature description"
      description: "Describe the feature you'd like to add or improve."
      placeholder: "Describe the new feature here..."

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Add more details here..."

  - type: checkboxes
    id: priority
    attributes:
      label: "Feature priority"
      options:
        - label: "Critical"

